import re

# SQL keywords that should NEVER be executed
FORBIDDEN_KEYWORDS = {
    "drop",
    "delete",
    "update",
    "insert",
    "alter",
    "truncate",
    "create",
    "replace",
    "grant",
    "revoke",
}


def clean_sql(sql: str) -> str:
    """
    Cleans the SQL generated by the LLM.

    - Removes markdown if present.
    - Removes extra whitespace.
    - Extracts the actual SQL statement.
    """

    sql = sql.strip()

    # Remove ```sql ... ```
    match = re.search(
        r"```(?:sql)?\s*(.*?)```",
        sql,
        re.DOTALL | re.IGNORECASE,
    )

    if match:
        sql = match.group(1)

    # Remove leading/trailing whitespace
    sql = sql.strip()

    return sql


def is_safe_sql(sql: str) -> bool:
    """
    Ensures only SELECT queries are allowed.
    """

    sql_lower = sql.lower().strip()

    # Must start with SELECT
    if not sql_lower.startswith("select"):
        return False

    # Check for forbidden keywords
    for keyword in FORBIDDEN_KEYWORDS:
        if re.search(rf"\b{keyword}\b", sql_lower):
            return False

    return True


def validate_sql(sql: str) -> str:
    """
    Cleans and validates SQL.
    Raises an exception if unsafe.
    """

    sql = clean_sql(sql)

    if not is_safe_sql(sql):
        raise ValueError(
            f"Unsafe SQL generated:\n{sql}"
        )

    return sql